name: merge_map
description: Combine multiple Maps into one. Equivalent to Object.assign in JS.
version: 1.0.0
homepage: https://github.com/thosakwe/merge_map
author: Tobe O <thosakwe@gmail.com>
dev_dependencies:
  test: ">= 0.12.13 < 0.13.0"