name: merge_map
description: Combine multiple Maps into one. Equivalent to Object.assign in JS.
version: 1.0.2
homepage: https://github.com/thosakwe/merge_map
author: Tobe O <thosakwe@gmail.com>
environment:
  sdk: ">=1.8.0 <3.0.0"
dev_dependencies:
  test:
